name: "Podcast Generator"
author: " Tiziana Bassi"
desacription: "Generates a feed"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.author }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.author }}